### ISSUE TITLE
Issue with whisper

### ISSUE THREAD

**Issue by wong251440** [langschain/Autogen_Video_Refinement#2]
(venv) C:\Users\User\Autogen_Video_Refinement>py main.py
Traceback (most recent call last):
  File "C:\Users\User\Autogen_Video_Refinement\main.py", line 3, in <module>
    import whisper
  File "C:\Users\User\venv\Lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\ctypes\__init__.py", line 369, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by wong251440** [comment]
Found what happened. 
Shoud be openai-whisper instead of whisper inside the requirements.txt
